### ISSUE TITLE
Add setting to use latest snapshot or latest stable automatically

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals-sublime#61]
Accept `latest-stable` or `latest-snapshot`  as server version and fetch version number from maven like https://github.com/scalameta/nvim-metals/pull/276

**Comment by rchl** [comment]
Personally I don't think that's a great idea because that means the server will change on users at random times and might break. Also it now will make a blocking request on every start which will slow down things.

I also recently wrote my thoughts about that at https://github.com/sublimelsp/LSP-marksman/issues/5#issuecomment-1237433020
